### ISSUE TITLE
0.18 plan

### ISSUE THREAD

**Issue by raiguard** [raiguard/Factorio-Tapeline#2]
Despite having source access and knowing that 0.18 was coming very soon, this still crept up on me like a predator and mauled me to bits. I'm going to have to rush to finish the refactor so I can release this mod to the hungry players!

## To-do
- [x] Undo GUI templating integration (the event handling is broken)
- [x] Implement mod settings
- [x] Test multiplayer and make sure everything works
- [x] Do a once-over of the code and optimise where possible
- [x] Release!
